controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number